service: good-duck-server

plugins:
  - serverless-plugin-typescript
  - serverless-plugin-optimize
  - serverless-prune-plugin
  - serverless-offline

provider:
  name: aws
  region: ap-northeast-2
  runtime: nodejs14.x
  stage: dev

functions:
  main:
    handler: src/lambda.handler
    events:
      - http:
          method: any
          path: /{any+}

package:
  patterns:
    - '!node_modules/.prisma/client/libquery_engine-*'
    - 'node_modules/.prisma/client/libquery_engine-rhel-*'
    - '!node_modules/prisma/libquery_engine-*'
    - '!node_modules/@prisma/engines/**'
